2020-05-23 15:12:51,373 ERROR: Exception on /api/users/4 [GET] [in /Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erinjohnson/Development/tiny_blog/app/api/users.py", line 7, in get_user
    return jsonify(User.query_or_404(id).to_dict())
AttributeError: type object 'User' has no attribute 'query_or_404'
2020-05-23 15:13:33,063 ERROR: Exception on /api/users [GET] [in /Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-05-23 15:13:36,878 ERROR: Exception on /api/users/1 [GET] [in /Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erinjohnson/Development/tiny_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erinjohnson/Development/tiny_blog/app/api/users.py", line 7, in get_user
    return jsonify(User.query_or_404(id).to_dict())
AttributeError: type object 'User' has no attribute 'query_or_404'
2020-05-23 15:14:00,669 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 15:16:48,533 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 15:18:53,515 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 15:20:23,063 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 15:22:31,371 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 16:56:59,429 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 16:57:05,641 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
2020-05-23 17:40:12,192 INFO: Tinyblog startup [in /Users/erinjohnson/Development/tiny_blog/app/__init__.py:81]
